name: Deployment using Tomcat
on: workflow_dispatch
  # workflow_run:
  #   workflows: Build and Sonar
  #   types: [completed]
jobs:
  Deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps: 
      # - name: Download the build artifact from triggered workflow 
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     run_id: ${{ github.event.workflow_run.id }}
      #     path: ./calculator
      #     search_artifacts: true
      - name: Download artifact
        run: gh release download Java-Web-Calculator --pattern "calculator.war"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: |
          ls
          cd calculator/
          ls
          cd */
          ls
          pwd

      - name: Deploy to Tomcat
        run: curl -v -u ${{secrets.TOMCAT_USR}}:${{secrets.TOMCAT_PWD}} -T /home/runner/work/Java-Web-Calculator/Java-Web-Calculator/calculator/*/*.war http://54.206.111.223:8080/manager/text/deploy?path=/calculator-webapp-war  
      