name: Deployment using Tomcat
on: 
  workflow_run:
    workflows: Build and Sonar
    types: [completed]
jobs:
  Deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps: 
      - name: Download the build artifact from triggered workflow 
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: ./calculator
          search_artifacts: true
      - run: |
          ls
          cd calculator/
          ls
          cd */
          ls
          pwd