name: Build and Sonar
on: 
  workflow_dispatch:
    inputs:
      environment: 
        description: Environment for deploy
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Test
          - Prod
jobs: 
  Build: 
    environment: ${{github.events.inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # - name: Git Version
      #   id: version
      #   uses: codacy/git-version@2.7.1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Nimisha-Chonattil_Java-Web-Calculator -Dsonar.qualitygate.wait=true
      - name: uploading artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: calculator-artifact
          path: target/*.war
      - run: |
          ls
          cd target/
          ls
          pwd
  Upload_to_release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: calculator-artifact
          
      - run: |
          ls
          pwd


      - name: Archive release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'calculator.zip'
      - run: |
          ls
          pwd 


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
          release_name: Release ${{ github.run_number}} 

    
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./calculator.zip
          asset_name: calculator-${{ github.run_number}}
          asset_content_type: application/zip

      
      


  # Upload_to_Release:

  #   needs: Build 
  #   runs-on: ubuntu-latest
  #   steps:   
      # - name: Downloading artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: calculator-artifact
      # - run: |
      #     ls
      #     pwd
      # - name: Archive release
      #   uses: thedoctor0/zip-release@0.7.5
      #   with:
      #     type: 'zip'
      #     filename: 'app.zip'
      # - run: |
      #     ls
      #     pwd

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ github.run_number }}
      #     draft: false
      #     prerelease: false
      #     release_name: Release ${{ github.run_number}}
          
    
        

      # - name: Upload release asset
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./app.zip
      #     asset_name: calculator-artifact-${{ github.run_number}}
      #     asset_content_type: application/zip

      













      